### ISSUE TITLE
Wire up the download buttons to the Preprint PDFs

### ISSUE THREAD

**Issue by scottaubrey** [elifesciences/enhanced-preprints-client#100]

**Comment by BlueReZZ** [comment]
@ryandixpeek suggests the latest changes will be ready by Weds (12th Oct). We'll then review those with the other stakeholders as a cursory check before uploading them somewhere useful.

**Comment by ryandixpeek** [comment]
The updated PDFs examples are available here; https://pagedjs.pages.gitlab.coko.foundation/elife-pagedjs/
