### ISSUE TITLE
Add Figure and Table Caption styling to client(text and title)

### ISSUE THREAD

**Issue by Maelplaine** [elifesciences/enhanced-preprints-client#42]
[See InVision Mockup](https://projects.invisionapp.com/d/main#/console/22074193/468216111/preview)

![image](https://user-images.githubusercontent.com/39725642/183871750-c5657f57-b1bc-4ccd-872a-c9ed83a2c84c.png)

### Tasks

- [ ] Style text
- [ ] Style title
- [ ] Add java script for expanding / hiding content on caption

**Comment by scottaubrey** [comment]
The basics of this was done with https://github.com/elifesciences/enhanced-preprints-client/pull/73
