### ISSUE TITLE
Add tabs for Article, Figures and Data and Peer Reviews page (prototype 3)

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/enhanced-preprints-client#49]
Tabs to mirror Journal to ensure users know both Journal and EPP are the "same" platform

**Comment by QueenKraken** [comment]
Require spikes to investigate how this work can be broken down, with corresponding tickets. @scottaubrey let me know when we can regroup

**Comment by QueenKraken** [comment]
Tabs are in EPP now.
