### ISSUE TITLE
Add menu(s) to match new menu on journal

### ISSUE THREAD

**Issue by chris-huggins** [elifesciences/enhanced-preprints-client#50]
Ensure menus are aligned across both Journal and EPP. Next step to reduce duplication of dev across two platforms for single changes

**Comment by QueenKraken** [comment]
Dependency on Journal work being completed (Endava) before this is completed. Work can be started but needs to mirror Journal.

**Comment by discodavey** [comment]
> Dependency on Journal work being completed (Endava) before this is completed. Work can be started but needs to mirror Journal.

I am using the html but creating the CSS near enough from scratch so it's leaner than in Pattern Library

**Comment by discodavey** [comment]
> @discodavey is the dependency on Endava still there (and what do I need to focus attention on to support you?) or are you able to work independently?

I am working independently. I am following the PR example that they have done for positioning so if any changes come through then I will see them and I will adjust mine to be the same.
