### ISSUE TITLE
Add icons as SVG's into project

### ISSUE THREAD

**Issue by discodavey** [elifesciences/enhanced-preprints-client#66]
# Description

Currently the icons are being brought in via classes using spans. We need to put the icons as SVG's into the project and then place them in the links etc as background images.

# Subtasks

- [ ] Download icons as svg's
- [ ] Add svg's into classes as background images for buttons etc

# Definition of Done

- [ ] All icons as svg's in project and added to classes for buttons etc

**Comment by scottaubrey** [comment]
This is now ongoing, and "done" for things we've worked on so far
